extends RefCounted

## Shared dimensions keep the imported meter-scaled body and pixel-space contacts aligned.

const UNITS_PER_METER := 106.0 / 2.53
const SOURCE_TIRE_RADIUS := 0.324
const SOURCE_AXLE_HEIGHT := 0.323
const SOURCE_HALF_TRACK := 0.744
const SOURCE_HALF_WIDTH := 0.85
const WHEEL_RADIUS := SOURCE_TIRE_RADIUS * UNITS_PER_METER
const AXLE_MOUNT_HEIGHT := 14.0
const AXLES: Array[Vector2] = [
	Vector2(-53, AXLE_MOUNT_HEIGHT), Vector2(53, AXLE_MOUNT_HEIGHT),
]
const GRAVITY := 980.0
const SPRING_STIFFNESS := 160.0
const SPRING_DAMPING := 12.0
const REST_LENGTH := 11.5
const MIN_LENGTH := 6.75
const MAX_LENGTH := 14.5
const STATIC_LENGTH := REST_LENGTH - GRAVITY / (2.0 * SPRING_STIFFNESS)
const RIDE_HEIGHT := AXLE_MOUNT_HEIGHT + STATIC_LENGTH + WHEEL_RADIUS
const BODY_ORIGIN_HEIGHT := (
	(AXLE_MOUNT_HEIGHT + STATIC_LENGTH) / UNITS_PER_METER + SOURCE_AXLE_HEIGHT
)
const ROOF: Array[Vector2] = [
	Vector2(-1.78, BODY_ORIGIN_HEIGHT - 1.64) * UNITS_PER_METER,
	Vector2(-0.35, BODY_ORIGIN_HEIGHT - 1.675) * UNITS_PER_METER,
	Vector2(0.64, BODY_ORIGIN_HEIGHT - 1.65) * UNITS_PER_METER,
]
const BODY_CONTACTS: Array[Vector2] = [
	Vector2(-1.94, BODY_ORIGIN_HEIGHT - 0.245) * UNITS_PER_METER,
	Vector2(-0.15, BODY_ORIGIN_HEIGHT - 0.20) * UNITS_PER_METER,
	Vector2(2.02, BODY_ORIGIN_HEIGHT - 0.245) * UNITS_PER_METER,
]
